"""Structured reply blocks.

The agent's answer is prose, but a tool result is data. Flattening an order lookup into a
sentence throws that structure away and the customer has to read a paragraph to find a tracking
number. So a reply is a list of blocks: text the model wrote, plus cards built in code from the
tool results. Cards are never generated by the model — they are rendered from the same DTOs the
orders module returns, so a card cannot say something the data does not.
"""

from datetime import date, datetime
from typing import Annotated, Literal
from urllib.parse import quote

from pydantic import BaseModel, Field

from app.orders.models import OrderStatusEnum
from app.orders.schemas import OrderStatus, ProductInfo

# Public tracking pages. A carrier we don't know simply gets no link.
TRACKING_URLS: dict[str, str] = {
    "blue dart": "https://www.bluedart.com/tracking?awb={n}",
    "delhivery": "https://www.delhivery.com/track/package/{n}",
    "dhl express": "https://www.dhl.com/in-en/home/tracking.html?tracking-id={n}",
    "fedex": "https://www.fedex.com/fedextrack/?trknbr={n}",
}

# The journey shown on an order card, in order.
JOURNEY: tuple[tuple[str, str], ...] = (
    ("placed", "Order placed"),
    ("packed", "Packed"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
)

# How far along each status is. -1 means the journey doesn't apply (cancelled, refunded…).
REACHED: dict[OrderStatusEnum, int] = {
    OrderStatusEnum.processing: 1,
    OrderStatusEnum.shipped: 2,
    OrderStatusEnum.delivered: 3,
    OrderStatusEnum.return_requested: 3,
    OrderStatusEnum.cancelled: -1,
    OrderStatusEnum.refunded: -1,
}

STATUS_LABEL: dict[OrderStatusEnum, str] = {
    OrderStatusEnum.processing: "Being packed",
    OrderStatusEnum.shipped: "On its way",
    OrderStatusEnum.delivered: "Delivered",
    OrderStatusEnum.cancelled: "Cancelled",
    OrderStatusEnum.return_requested: "Return requested",
    OrderStatusEnum.refunded: "Refunded",
}

# Tone drives colour in the widget; it is not decoration, it tells the customer what happened.
Tone = Literal["normal", "handoff", "notice"]


class TextBlock(BaseModel):
    type: Literal["text"] = "text"
    text: str
    tone: Tone = "normal"
    sources: list[str] = Field(default_factory=list)


class Step(BaseModel):
    label: str
    state: Literal["done", "current", "pending"]


class CardLine(BaseModel):
    name: str
    quantity: int


class OrderCardBlock(BaseModel):
    type: Literal["order_card"] = "order_card"
    number: str
    status: str
    status_label: str
    steps: list[Step] = Field(default_factory=list)
    items: list[CardLine] = Field(default_factory=list)
    placed_on: str = ""
    eta: str | None = None
    carrier: str | None = None
    tracking_number: str | None = None
    tracking_url: str | None = None


class ProductCardBlock(BaseModel):
    type: Literal["product_card"] = "product_card"
    sku: str
    name: str
    category: str
    description: str
    price_label: str
    in_stock: bool
    stock_label: str


class QuickRepliesBlock(BaseModel):
    type: Literal["quick_replies"] = "quick_replies"
    options: list[str] = Field(default_factory=list)


Block = Annotated[
    TextBlock | OrderCardBlock | ProductCardBlock | QuickRepliesBlock,
    Field(discriminator="type"),
]


# Offered after an order card. All three are things a customer actually does next, and the
# first two hand over to a human by design — the agent never acts on them itself.
ORDER_FOLLOW_UPS = ["I need to return this", "Change my delivery address", "Talk to a person"]


def tracking_url(carrier: str | None, number: str | None) -> str | None:
    if not carrier or not number:
        return None
    template = TRACKING_URLS.get(carrier.strip().lower())
    # safe="" so a slash in a tracking number cannot escape the query parameter.
    return template.format(n=quote(number.strip(), safe="")) if template else None


def order_card(order: OrderStatus) -> OrderCardBlock:
    return OrderCardBlock(
        number=order.number,
        status=order.status.value,
        status_label=STATUS_LABEL.get(order.status, order.status.value),
        steps=_steps(order.status),
        items=[CardLine(name=i.name, quantity=i.quantity) for i in order.items],
        placed_on=_day(order.placed_at),
        eta=_day(order.eta) if order.eta else None,
        carrier=order.carrier,
        tracking_number=order.tracking_number,
        tracking_url=tracking_url(order.carrier, order.tracking_number),
    )


def product_card(product: ProductInfo) -> ProductCardBlock:
    if not product.in_stock:
        stock = "Out of stock"
    elif product.stock <= 5:
        stock = f"Only {product.stock} left"
    else:
        stock = "In stock"
    return ProductCardBlock(
        sku=product.sku,
        name=product.name,
        category=product.category,
        description=product.description,
        price_label=f"₹{product.price:,.0f}",
        in_stock=product.in_stock,
        stock_label=stock,
    )


def _steps(status: OrderStatusEnum) -> list[Step]:
    reached = REACHED.get(status, -1)
    if reached < 0:
        return []
    out: list[Step] = []
    for index, (_, label) in enumerate(JOURNEY):
        if index < reached:
            state: Literal["done", "current", "pending"] = "done"
        elif index == reached:
            state = "current"
        else:
            state = "pending"
        out.append(Step(label=label, state=state))
    return out


def _day(value: datetime | date) -> str:
    return f"{value:%d %b %Y}"
